steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=${REPO_NAME}"]
    args: ["install", "."]
    id: "go-install"
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME}", "."]
    id: "docker-build"

images: ['gcr.io/${PROJECT_ID}/${REPO_NAME}:${TAG_NAME}']